import {ArrowRight,FileCheck2} from 'lucide-react';
import {Button,Panel} from './components';import {date} from './format';import {nextDeskAction} from './action-desk';import type {ChainState} from './types';
export function NextActionDesk({state,issuer,blocked,onCapture,onRedemption,onClaims,onIssuer,onNewDemo}:{state:ChainState;issuer:boolean;blocked:boolean;onCapture:()=>void;onRedemption:()=>void;onClaims:()=>void;onIssuer:()=>void;onNewDemo?:()=>void}){
  const action=nextDeskAction(state),issue=state.instrument!;
  const scheduled=state.coupons.find(c=>c.status==='scheduled');
  const unpaid=state.coupons.find(c=>c.snapshotAddress&&BigInt(c.paidMinor)<BigInt(c.totalMinor));
  const heading={capture:'Capture the next record date',coupon:'Recorded coupons remain payable','coupon-wait':'Coupon payment is scheduled','record-wait':'Next coupon record date',redemption:'Open principal redemption',principal:'Principal claims are open','maturity-wait':'Awaiting maturity',settled:'Instrument settled',draft:'Complete issue setup',unavailable:'Chain state unavailable'}[action];
  const detail={capture:'Create the next immutable rights snapshot. Later transfers preserve each previously captured coupon.',coupon:'Holders claim their recorded allocations, including rights that remain after bond retirement.','coupon-wait':'The entitlement is recorded. Claims open at the payment time below.','record-wait':'The next snapshot has not opened yet. Existing captured rights remain unchanged.',redemption:'All scheduled snapshots are captured. Freeze maturity positions for principal payment and retirement.',principal:'Each entitled holder redeems its principal; payment and burn happen in the same transaction.','maturity-wait':'Coupon duties are settled. Principal redemption opens at the instrument maturity time.',settled:'All recorded coupon duties and issued principal are settled.',draft:'Register holders, place bonds and prefund every obligation before activation.',unavailable:'Read the test chain before preparing another transaction.'}[action];
  const record=scheduled?.recordAt??unpaid?.recordAt,deadline=action==='maturity-wait'||action==='redemption'||action==='principal'?issue.maturityAt:unpaid?.paymentAt??scheduled?.paymentAt;
  return <Panel title="Next corporate action" label="Action desk" className="next-action"><span className="action-icon"><FileCheck2 size={26} strokeWidth={1.5} aria-hidden="true"/></span><h3>{heading}</h3><p>{detail}</p><dl className="compact-facts">{record&&<div><dt>Record date</dt><dd>{date(record,true)}</dd></div>}{deadline&&<div><dt>{['maturity-wait','redemption','principal'].includes(action)?'Maturity':'Payment date'}</dt><dd>{date(deadline,true)}</dd></div>}</dl>{action==='capture'?<Button variant="primary" disabled={blocked||!issuer} onClick={onCapture}>Capture record date<ArrowRight size={16}/></Button>:action==='redemption'?<Button variant="primary" disabled={blocked||!issuer} onClick={onRedemption}>Open redemption<ArrowRight size={16}/></Button>:action==='coupon'||action==='principal'?<Button variant="primary" onClick={onClaims}>Open holder claims<ArrowRight size={16}/></Button>:action==='draft'?<Button variant="primary" onClick={onIssuer}>Open issuer desk<ArrowRight size={16}/></Button>:action==='settled'&&onNewDemo?<Button onClick={onNewDemo}>New test issue<ArrowRight size={16}/></Button>:<Button variant="secondary" onClick={onClaims}>Review recorded rights</Button>}{action==='capture'&&!issuer&&<p className="control-hint">Issuer view can initiate capture; holders keep their own claim authority.</p>}</Panel>;
}
