import {createContext, useContext, useEffect, useState, type ReactNode} from 'react';
export type UiLanguage='ru'|'en';
const words:Record<string,string>={
  'Portfolio':'Портфель',
  'Account':'Аккаунт',
  'Skip to content':'К содержимому','BondTrace overview':'Обзор BondTrace','Main navigation':'Разделы кабинета','Interface language':'Язык интерфейса','Further submissions are paused until its network status is known.':'Новые операции доступны после проверки предыдущей.',
  'No coupon recorded yet':'Держатели ещё не зафиксированы','The payout registry appears here after the issuer captures the record date.':'После фиксации держателей здесь появятся права на купон.','Open all activity':'Все операции','holders':'держателей','bonds':'облигаций','Registered holders and current positions':'Держатели и текущие облигации','The registry is empty':'Держателей пока нет','Issue bonds to registered holders before capturing corporate-action rights.':'Сначала зарегистрируйте держателей и разместите облигации.',
  'Capture the record date first':'Сначала зафиксируйте держателей','Coupon claims become available after the issuer freezes rights and the payment condition is met.':'Купон доступен после фиксации держателей и наступления даты выплаты.','Principal redemption is not open':'Погашение пока не открыто','One ballot per holder. Voting weight comes from a fixed on-chain snapshot.':'Один голос на держателя. Вес зависит от количества облигаций на дату фиксации.','Proposal':'Предложение','The issuer can open a proposal for this issue. Each registered holder gets an immutable voting allocation.':'Эмитент создаёт предложение. Вес голоса каждого держателя фиксируется.',
  'Chain accounts are the source of rights.':'Права подтверждены данными блокчейна.','· 6 decimal settlement units':'· точность расчёта до 6 знаков','Every action leaves a receipt.':'Квитанция для каждой операции','Signed transaction references appear here. Confirmation is separate from submission; older receipts may retain a previously recorded confirmation.':'Здесь находятся подписанные операции и их подтверждения.','Program account':'Адрес программы','Instrument account':'Адрес выпуска','No chain state available':'Данные сети недоступны','Connect the API and RPC to read confirmed activity.':'Восстановите связь с сетью и обновите данные.',
  'Registered recipient':'Получатель','Choose a registered holder':'Выберите держателя','Reading the instrument from Solana':'Загрузка выпуска','Your bond workspace':'Кабинет облигаций','Create an issue, register its holders and manage every payment from one place.':'Создайте выпуск, добавьте держателей и управляйте выплатами.','Create an issue':'Создать выпуск','Open example workspace':'Открыть пример','Start with the issuer desk':'Начните с создания выпуска','Define the issue':'Задайте условия','Set the nominal value, coupon schedule and settlement token.':'Укажите номинал, купоны и способ расчёта.','Place and reserve':'Разместите облигации','Register holders, allocate bonds and fully fund the obligations.':'Добавьте держателей, распределите облигации и пополните резерв.','Service corporate actions':'Управляйте выплатами','Record entitlements, approve payments and inspect confirmed receipts.':'Фиксируйте права, проводите выплаты и проверяйте квитанции.',
  'Selected issue terms':'Условия выпуска','Registered bond issue ·':'Выпуск облигаций ·','bonds placed':'облигаций размещено','Instrument lifecycle':'Этапы выпуска','Completed':'Завершено','% paid':'% выплачено','Fixed entitlement and settlement status by holder':'Права держателей и статус выплат','No eligible allocations':'Начислений нет','This snapshot contains no holder entitlements.':'На эту дату права держателей не определены.','No confirmed activity yet':'Подтверждённых операций пока нет','Real transaction receipts appear after the first on-chain action.':'Квитанции появятся после первой операции.',
  'Connect to see your entitlements':'Подключите кошелёк','The registry is visible without a wallet. Connect your account to read its positions and approve claims.':'Подключите кошелёк, чтобы увидеть свои облигации и получить выплаты.','Waiting for the record date':'Ожидается дата фиксации','Your coupon allocation appears after the issuer captures the holder registry.':'Начисление появится после фиксации держателей эмитентом.','Transferring a bond changes your current position. A past coupon or vote still uses the owner and quantity fixed in its snapshot.':'Облигации можно передать. Права на уже начисленный купон и голосование остаются у прежнего владельца.','Generated at initialization':'Создаётся при выпуске','Nominal per bond:':'Номинал:','settlement units · Maturity':'единиц расчёта · Погашение','per bond · Record':'на облигацию · Фиксация','· Payment':'· Выплата',
  'Overview':'Обзор','Holder registry':'Держатели','Payments':'Выплаты','My portfolio':'Мой портфель','Holder voting':'Голосования','Voting':'Голосования','Issuer desk':'Эмитент',
  'Issuer':'Эмитент','Investor 01':'Держатель 1','Investor 02':'Держатель 2','Investor 03':'Держатель 3','Workspace':'Кабинет','Corporate actions':'Обслуживание облигаций',
  'Receipts & activity':'Операции и квитанции','Connect wallet':'Подключить кошелёк','Selected issue':'Выпуск','Signing mode':'Подписание','My wallet':'Мой кошелёк','Workspace accounts':'Аккаунты примера','Generated signers':'Созданные аккаунты','Acting as':'Аккаунт',
  'Choose an account':'Выберите аккаунт','Your wallet':'Ваш кошелёк','Example accounts':'Аккаунты примера','Use my wallet':'Использовать мой кошелёк','Disconnect wallet':'Отключить кошелёк','Your connected wallet':'Ваш кошелёк','Connect your wallet':'Подключите кошелёк','Wallet connection':'Подключение кошелька',
  'Refresh chain state':'Обновить данные','Registered bond':'Облигации','RPC offline':'Нет связи','No compatible wallet detected':'Кошелёк не найден','Wallets on Solana':'Кошельки Solana','Close dialog':'Закрыть окно',
  'Cancel':'Отмена','Close':'Закрыть','Continue':'Продолжить','Back':'Назад','Review action':'Проверить операцию','Review operation':'Проверка операции','Copy full address':'Скопировать адрес','Address copied':'Адрес скопирован','No chain data':'Нет данных',
  'Recorded rights':'Права на выплату','Issue status, reserved funds and the next action.':'Состояние выпуска и ближайшее действие.','Current positions and fixed record-date entitlements.':'Облигации держателей и права на выплаты.','Coupon allocations, principal repayment and confirmed claims.':'Купоны, возврат номинала и оплаченные требования.','Your bond positions and eligible payments.':'Ваши облигации и доступные выплаты.','Proposals and ballots with recorded holder weights.':'Предложения и голоса держателей.','Create, place and activate a bond issue.':'Создайте и разместите выпуск облигаций.',
  'Bond issue':'Выпуск облигаций','Redeemed':'Погашен','Redemption open':'Погашение открыто','Active':'Активен','Draft':'Черновик','Nominal per bond':'Номинал облигации','Coupon per bond':'Купон на облигацию','Annual coupon':'Годовой купон','Maturity':'Дата погашения','Issue account':'Адрес выпуска',
  'Issued':'Размещён','Record date':'Фиксация держателей','Coupon':'Купон','All claims settled':'Все выплаты завершены','Outstanding principal':'Остаток номинала','Coupon recorded':'Купон к выплате','Settlement vault':'Резерв выплат','Settlement reconciliation':'Сверка выплат','Latest coupon':'Выбранный купон','All payments':'Все выплаты','Latest confirmations':'Последние операции','Chain activity':'Подтверждённые операции',
  'Recorded entitlement':'Начислено','Confirmed paid':'Выплачено','Remaining':'Осталось','Entitled holder':'Держатель','Recorded bonds':'Облигации на дату фиксации','Allocation':'Сумма','Settlement':'Статус','Paid':'Выплачено','Unclaimed':'Не получено','You':'Вы','Bonds':'Облигации','Wallet address':'Адрес кошелька','Registered holder':'Держатель','Face-value position':'Общий номинал','Status':'Статус','Registered':'Зарегистрирован','Selected account':'Выбранный аккаунт','Your account':'Ваш аккаунт','Registered address':'Адрес держателя',
  'Capture record date':'Зафиксировать держателей','Fixed coupon rights':'Права на купон','Record-date snapshot':'Состав держателей на дату фиксации','Immutable entitlement':'Права зафиксированы','Record slot':'Блок фиксации','Snapshot account':'Адрес реестра','Settlement account':'Счёт выплат','Add reserve':'Пополнить резерв','Vault reserve':'Резерв выплат','Principal obligation':'Номинал к возврату','Recorded coupon unpaid':'Неоплаченный купон','Payout registry':'Реестр выплат','Principal':'Номинал','Open redemption':'Открыть погашение','Claims are paid once':'Повторная выплата исключена',
  'Transfer bonds':'Передать облигации','Current holding':'Ваши облигации','Outstanding face value':'Непогашенный номинал','Claimable coupon now':'Доступно к получению','Your corporate actions':'Ваши выплаты','Recorded rights and settlement status':'Начисления и статус оплаты','Workspace account':'Аккаунт примера','Connected wallet':'Подключённый кошелёк','Coupon payment':'Выплата купона','Principal redemption':'Возврат номинала','Claim':'Получить','settlement units':'единиц расчёта','Registered bond units':'Облигации выпуска',
  'Current holdings and recorded rights are separate':'После передачи право на прошлый купон сохраняется','Holder decisions':'Решения держателей','Create proposal':'Создать предложение','No holder proposals yet':'Предложений пока нет','Create the first proposal':'Создать предложение','Voting open':'Приём голосов','Closed':'Закрыто','Closes':'Голосование до','Your fixed weight':'Ваш вес голоса','Snapshot':'Реестр голосующих','For':'За','Against':'Против','Vote against':'Против','Vote for':'За','Ballot recorded':'Голос учтён',
  'Network':'Сеть','Signing authority':'Кто подписывает','Signer address':'Адрес подписанта','Settlement amount':'Сумма','Bond quantity':'Количество облигаций','Recipient':'Получатель','Token mint':'Адрес расчётного токена','Network fee':'Комиссия сети','Not quoted by API':'Не определена','Simulation':'Проверка операции','Passed':'Успешно','Not verified':'Не проверена','Recovery reference':'Номер операции','Real transaction signature':'Подпись операции','Reviewed immutable terms':'Условия перед созданием','Sign in wallet':'Подписать в кошельке','Approve workspace operation':'Подтвердить операцию','Resume workspace setup':'Продолжить настройку','Resume operation':'Продолжить операцию','Check existing signature':'Проверить подпись','Read chain state':'Обновить данные',
  'Review before signing':'Проверьте перед подписью','Preparing & simulating':'Проверяем операцию','Waiting for your wallet':'Ожидаем подпись кошелька','Waiting for confirmation':'Ожидаем подтверждение сети','Confirmed on Solana':'Операция подтверждена','Operation not completed':'Операция не выполнена','Signature cancelled':'Подпись отменена','Network status unknown':'Подтверждение пока неизвестно',
  'Read state again':'Обновить данные','Check connection':'Проверить связь','One operation needs verification':'Проверьте предыдущую операцию','Check operation':'Проверить операцию','No automatic retry. Check the existing receipt and current state before signing anything else.':'Операция не отправляется повторно. Сначала проверьте её состояние.',
  'The receipt is confirmed. The view now reads the updated chain state.':'Подтверждение получено. Данные выпуска обновлены.','Workspace mode uses generated sandbox signers. Switch to My wallet to approve signatures personally.':'Для примера используются отдельно созданные аккаунты. Ваш кошелёк подтверждает подписи самостоятельно.',
  'Your wallet keeps your keys and approves every signature. Workspace accounts use separate generated sandbox signers.':'Ключи остаются в вашем кошельке. Вы подтверждаете каждую подпись.','Signatures approved in your wallet':'Подписи подтверждаются в кошельке','Connect to approve operations':'Подключите кошелёк для операций',
  'Each eligible holder signs their own claim. A confirmed receipt marks the allocation as paid; another claim is rejected by the program.':'Держатель получает свою выплату и подтверждает её кошельком. Программа не допускает повторную оплату.',
  'Current holdings come from chain accounts. A record-date snapshot creates separate, fixed rights.':'Здесь показаны текущие облигации. Права на купон сохраняются отдельно на дату фиксации.','Rights are fixed on chain. Payments are reconciled against actual confirmed claims.':'Начисления сверяются с подтверждёнными выплатами.','Covers current principal and scheduled coupons':'Покрывает оставшиеся выплаты','Compare reserve with scheduled obligations':'Проверьте, хватает ли средств на выплаты','Confirmed claims subtracted':'За вычетом полученных выплат','No coupon snapshot yet':'Держатели ещё не зафиксированы','Claims open at each recorded payment time':'После наступления даты выплаты','Current holding × face value':'Количество × номинал','Outstanding units × face value':'Количество × номинал',
  'Next step':'Следующее действие','Complete':'Завершено','Issuer action':'Действие эмитента','Scheduled':'По расписанию','Holder action':'Действие держателя','Setup':'Настройка','Unavailable':'Недоступно','Create another issue':'Создать выпуск','Open holder claims':'Перейти к выплатам','Open issuer desk':'Настроить выпуск','Review recorded rights':'Посмотреть права на выплаты',
};
const Context=createContext({language:'en' as UiLanguage,setLanguage:(_language:UiLanguage)=>{},t:(text:string)=>text});
export function UiLanguageProvider({children}:{children:ReactNode}){
  const [language,setLanguage]=useState<UiLanguage>(()=>{try{return localStorage.getItem('bondtrace.language')==='ru'?'ru':'en';}catch{return 'en';}});
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem('bondtrace.language',language);}catch{}},[language]);
  return <Context.Provider value={{language,setLanguage,t:(text)=>language==='ru'?words[text]??text:text}}>{children}</Context.Provider>;
}
export const useUiLanguage=()=>useContext(Context);
