const selector=document.getElementById('snapshot'),status=document.getElementById('data-status'),rows=document.getElementById('allocations'),retry=document.getElementById('retry');let evidence;
// Detailed test settlement amounts use the instrument's actual precision; no float conversion.
function money(value,decimals){if(typeof value!=='string'||!/^\d+$/.test(value))return '—';const n=BigInt(value),scale=10n**BigInt(decimals);return (n/scale).toLocaleString('en-US')+(decimals?'.'+(n%scale).toString().padStart(decimals,'0'):'');}
const cell=(text,className)=>{const td=document.createElement('td');td.textContent=text;if(className)td.className=className;return td;};
function render(){const state=evidence.state,principal=selector.value==='principal',snapshot=principal?state.redemption:state.coupons[Number(selector.value)],decimals=state.instrument.settlementDecimals;
 rows.replaceChildren();for(const [index,e]of snapshot.entitlements.entries()){const tr=document.createElement('tr'),label=cell(state.holders[index]?.label??'Registered test holder'),address=document.createElement('small');address.textContent=e.wallet.slice(0,6)+'…'+e.wallet.slice(-5);label.append(address);tr.append(label,cell(e.units,'num'),cell(money(e.amountMinor,decimals),'num'),cell(e.claimed?'Confirmed paid':'Unclaimed',e.claimed?'paid':''));rows.append(tr);}
 document.getElementById('table-caption').textContent=principal?'Principal rights fixed at maturity':'Coupon '+(Number(selector.value)+1)+' rights fixed on record date';
 document.getElementById('snapshot-note').textContent=(principal?'Maturity positions are 8 / 7 bonds.':'Coupon '+(Number(selector.value)+1)+' total: '+money(snapshot.totalMinor,decimals)+' test units. Historical rights remain after the transfer and burn.')+' Captured from a completed localnet issue; current circulating supply is zero.';
}
async function load(){selector.disabled=true;retry.hidden=true;status.textContent='Loading saved evidence…';try{const response=await fetch('docs/evidence/backend-lifecycle-localnet.json',{cache:'no-cache'});if(!response.ok)throw Error('Evidence unavailable');const data=await response.json(),s=data.state;
 if(!s||s.network!=='localnet'||s.reconciliation?.status!=='verified'||s.instrument?.status!=='redeemed'||s.coupons?.length!==2||s.holders?.length!==2||!Number.isInteger(s.instrument.settlementDecimals)||s.instrument.settlementDecimals<0||s.instrument.settlementDecimals>12)throw Error('Evidence scope mismatch');
 const total=s.coupons.reduce((sum,c)=>sum+BigInt(c.paidMinor),0n);if(total!==1125000000n||BigInt(s.redemption.paidMinor)!==15000000000n||s.instrument.vaultBalanceMinor!=='0')throw Error('Evidence totals mismatch');
 evidence=data;document.querySelector('[data-total="coupon"]').textContent=money(total.toString(),s.instrument.settlementDecimals);document.querySelector('[data-total="principal"]').textContent=money(s.redemption.paidMinor,s.instrument.settlementDecimals);document.querySelector('[data-total="remaining"]').textContent=money(s.reconciliation.totals.remainingObligations.baseUnits,s.instrument.settlementDecimals);status.textContent='Saved, reconciled localnet outcome';selector.disabled=false;render();
 }catch{status.textContent='Evidence could not be loaded';rows.replaceChildren();const tr=document.createElement('tr'),td=cell('Use Retry or open the original JSON evidence below.');td.colSpan=4;tr.append(td);rows.append(tr);document.getElementById('snapshot-note').textContent='No financial values are substituted for unavailable data.';retry.hidden=false;}}
selector.addEventListener('change',render);retry.addEventListener('click',load);load();
