import {after,test} from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {address,getAddressDecoder,getAddressEncoder,getProgramDerivedAddress} from '@solana/kit';
import * as program from '../../packages/client/src/program.ts';
import type {CatalogRecord} from '../../server/catalog.ts';

// Real isolated SQLite and recovery code, synthetic confirmed RPC observations.
// No signer, financial relay, SBF or fabricated execution proof is used here.
process.env.BONDTRACE_DATA_DIR=path.resolve('.local/tests/v2-catalog-projection-'+crypto.randomUUID());
const [catalog,operations,journal,storage]=await Promise.all([import('../../server/catalog.ts'),import('../../server/operations.ts'),import('../../server/journal.ts'),import('../../server/storage.ts')]);
const oldFetch=globalThis.fetch;after(()=>{globalThis.fetch=oldFetch;storage.closeStorage();});
const key=(n:number)=>getAddressDecoder().decode(Uint8Array.from({length:32},(_,i)=>i<2?(n>>>(8*i))&255:31));
const pk=(s:string)=>Buffer.from(getAddressEncoder().encode(address(s))),issuer=key(1),settlement=key(2),genesis=key(3);
const u32=(v:number)=>{const b=Buffer.alloc(4);b.writeUInt32LE(v);return b;},u64=(v:bigint)=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(v);return b;},i64=(v:bigint)=>{const b=Buffer.alloc(8);b.writeBigInt64LE(v);return b;};
const disc=(s:string)=>createHash('sha256').update('account:'+s).digest().subarray(0,8),str=(s:string)=>[u32(Buffer.byteLength(s)),Buffer.from(s)];
function raw(name:string,size:number,parts:Uint8Array[]){const bytes=Buffer.concat([disc(name),...parts]);assert.ok(bytes.length<=size);return {owner:program.PROGRAM_ID,executable:false,data:[Buffer.concat([bytes,Buffer.alloc(size-bytes.length)]).toString('base64'),'base64']};}
async function fixture(series:bigint){
  const bond=await program.deriveBondV2(issuer,series),mint=await program.deriveBondMintV2(bond),vault=await program.deriveVaultV2(bond),bump=(await getProgramDerivedAddress({programAddress:program.PROGRAM_ID,seeds:[Buffer.from('bond_v2'),pk(issuer),u64(series)]}))[1];
  const accounts=new Map<string,ReturnType<typeof raw>>();accounts.set(bond,raw('BondV2',319,[Buffer.from([2]),pk(issuer),pk(mint),pk(settlement),pk(vault),u64(series),u64(1000n),Buffer.from([0xe8,3,2]),i64(2000n),u64(1n),u64(0n),Buffer.from([1,bump]),u64(1n),u32(513),u32(1),u32(1),u32(0),i64(1000n),i64(1000n),i64(1000n),i64(1100n),u64(50n),Buffer.from([3]),u32(513),...str('Projection cache fixture')]));
  const previous:CatalogRecord={protocolVersion:2,seriesId:String(series),bond,name:'Projection cache fixture',settlementMint:settlement,createdAt:'2026-10-08T00:00:00.000Z',rateBps:1000,couponFrequency:2,roles:{issuer},proposalIds:Array.from({length:512},(_,i)=>String(i+1)),complete:true,accelerated:false,source:'wallet'};
  return {bond,accounts,previous};
}
function transport(accounts:Map<string,ReturnType<typeof raw>>){let sends=0;globalThis.fetch=async(_url,init)=>{const r=JSON.parse(String(init?.body));let result:unknown;if(r.method==='getGenesisHash')result=genesis;else if(r.method==='getSignatureStatuses')result={context:{slot:101},value:[{err:null,slot:100,confirmationStatus:'confirmed'}]};else if(r.method==='getAccountInfo')result={context:{slot:101},value:accounts.get(r.params[0])??null};else if(r.method==='getTransaction')result=null;else if(r.method==='sendTransaction'){sends++;throw new Error('Recovery must never send');}else throw new Error('Unexpected synthetic RPC '+r.method);return Response.json({jsonrpc:'2.0',id:r.id,result});};return ()=>sends;}
async function retainedOperation(id:string,signature:string,bond:string,action:string,params:Record<string,unknown>){operations.beginOperation(id,action,'issuer',params);operations.updateOperation(id,{wallet:issuer,bond,signature,status:'unknown',chainStatus:'confirmed',projectionStatus:'pending'});journal.saveReceipt({signature,operationId:id,action,bond,wallet:issuer,network:'localnet',genesisHash:genesis,chainStatus:'confirmed',projectionStatus:'pending',submittedAt:'2026-10-10T00:00:00.000Z',slot:100,verification:'live-rpc',finality:{schemaVersion:1,signature,status:'confirmed',source:'live-rpc',slot:100,contextSlot:101,observedAt:'2026-10-10T00:00:00.000Z',genesisHash:genesis}});}

test('already-confirmed 513th proposal projects with the same recovery ID and signature without another relay',async()=>{
  const f=await fixture(401n),action=await program.deriveActionV2(f.bond,3,513);f.accounts.set(action,raw('ActionV2',235,[pk(f.bond),Buffer.from([3]),u32(513),i64(800n),i64(0n),u64(0n),i64(800n),i64(1900n),u32(513),u32(0),...Array.from({length:5},()=>u64(0n)),Buffer.from([0,255]),...str('513th proposal')]));catalog.saveCatalog(f.previous);
  const oldAction=await program.deriveActionV2(f.bond,3,1),oldSignature='d'.repeat(88);f.accounts.set(oldAction,raw('ActionV2',235,[pk(f.bond),Buffer.from([3]),u32(1),i64(700n),i64(0n),u64(0n),i64(700n),i64(1900n),u32(513),u32(0),...Array.from({length:5},()=>u64(0n)),Buffer.from([0,255]),...str('Retained old proposal')]));journal.saveReceipt({signature:oldSignature,action:'create_proposal_v2',bond:f.bond,account:oldAction,wallet:issuer,network:'localnet',genesisHash:genesis,chainStatus:'confirmed',projectionStatus:'complete',submittedAt:'2026-10-08T00:00:00.000Z'});const oldReceipt=journal.receipt(oldSignature);
  const sends=transport(f.accounts),id='projection_513_same_id',signature='a'.repeat(88);await retainedOperation(id,signature,f.bond,'create_proposal_v2',{proposalId:'513'});
  for(let i=0;i<3;i++){const result=await operations.operationStatus(id);assert.equal(result.signature,signature);assert.equal(result.operationId,id);assert.equal(result.projectionStatus,'complete');}
  const saved=catalog.readCatalog(f.bond)!;assert.equal(saved.proposalIds.length,512);assert.equal(saved.proposalIds[0],'2');assert.equal(saved.proposalIds.at(-1),'513');assert.equal(saved.discoveryWindow?.proposalHistoryTruncated,true);assert.equal(journal.receipt(signature)?.projectionStatus,'complete');assert.equal(operations.findOperation(id)?.signature,signature);assert.equal(sends(),0);assert.equal(f.accounts.has(action),true);assert.equal(f.accounts.has(oldAction),true);assert.deepEqual(journal.receipt(oldSignature),oldReceipt);
});
test('confirmed holder projection compacts optional labels while preserving identity and retained receipt',async()=>{
  const f=await fixture(402n),labels=Object.fromEntries(Array.from({length:512},(_,i)=>[key(i+100),'L'])),wallet=key(900),holder=await program.deriveHolderV2(f.bond,wallet);catalog.saveCatalog({...f.previous,holderLabels:labels});f.accounts.set(holder,raw('HolderV2',77,[pk(f.bond),pk(wallet),u32(512),Buffer.from([255])]));
  const sends=transport(f.accounts),id='projection_labels_same_id',signature='b'.repeat(88);await retainedOperation(id,signature,f.bond,'register_holder_v2',{holderWallet:wallet,label:'я'.repeat(32)});storage.closeStorage();
  for(let i=0;i<2;i++){const result=await operations.operationStatus(id);assert.equal(result.signature,signature);assert.equal(result.projectionStatus,'complete');}
  const saved=catalog.readCatalog(f.bond)!;assert.equal(Object.keys(saved.holderLabels!).length,128);assert.equal(saved.holderLabels![wallet],'я'.repeat(32));assert.equal(saved.discoveryWindow?.holderLabelsTruncated,true);assert.equal(saved.createdAt,f.previous.createdAt);assert.deepEqual(saved.roles,f.previous.roles);assert.equal(saved.source,f.previous.source);assert.equal(saved.seriesId,f.previous.seriesId);assert.equal(saved.rateBps,f.previous.rateBps);assert.equal(saved.couponFrequency,f.previous.couponFrequency);assert.equal(journal.receipt(signature)?.chainStatus,'confirmed');assert.equal(sends(),0);
});
test('projection helper bounds worst-case optional metadata, preserves immutable fields and sticky disclosure',async(t)=>{
  const {compactV2CatalogProjection}=await import('../../server/v2-catalog-projection.ts'),{rateTermsMemo}=await import('../../server/rate-terms.ts'),f=await fixture(403n),labels=Object.fromEntries(Array.from({length:513},(_,i)=>[key(i+100),'я'.repeat(32)])),descriptor={rateBps:'1000',couponFrequency:'2',couponUnitMinor:'50'},rateTerms={version:1 as const,faceValueMinor:'1000',...descriptor,creationSignature:'c'.repeat(88),memoSha256:createHash('sha256').update(rateTermsMemo(f.bond,issuer,'1000',descriptor)).digest('hex'),provenance:'issuer-signed-creation-memo' as const},roles={issuer,...Object.fromEntries(Array.from({length:16},(_,i)=>['R'+String(i).padStart(31,'x'),key(i+900)]))},input={...f.previous,name:'\\'.repeat(64),roles,rateTerms,bootstrapSignature:'e'.repeat(88),holderLabels:labels,proposalIds:Array.from({length:513},(_,i)=>String(4294967295-512+i))},compacted=compactV2CatalogProjection(input);
  assert.equal(compacted.proposalIds.length,512);assert.equal(Object.keys(compacted.holderLabels!).length,128);assert.ok(Buffer.byteLength(JSON.stringify(compacted))<32768);assert.equal(Object.keys(input.holderLabels).length,513);assert.deepEqual(compacted.discoveryWindow,{proposalLimit:512,holderLabelLimit:128,proposalHistoryTruncated:true,holderLabelsTruncated:true});assert.deepEqual(compactV2CatalogProjection(compacted),compacted);catalog.saveCatalog(compacted);assert.deepEqual(catalog.readCatalog(f.bond)?.discoveryWindow,compacted.discoveryWindow);
  assert.deepEqual(compacted.rateTerms,rateTerms);assert.deepEqual(compacted.roles,roles);assert.equal(compacted.createdAt,input.createdAt);assert.equal(compacted.source,input.source);const escaped=compactV2CatalogProjection({...compacted,holderLabels:Object.fromEntries(Object.keys(compacted.holderLabels!).map(k=>[k,'\\'.repeat(64)]))});assert.ok(Buffer.byteLength(JSON.stringify(escaped))<32768);catalog.saveCatalog(escaped);t.diagnostic(`Bounded catalog JSON: max UTF8 labels=${Buffer.byteLength(JSON.stringify(compacted))}B; max escaped labels=${Buffer.byteLength(JSON.stringify(escaped))}B; 512 IDs/128 labels/17 roles/rate evidence`);
  assert.deepEqual(compactV2CatalogProjection({...compacted,proposalIds:['0001','1','2']}).proposalIds,['1','2']);
});
