import {createHash} from 'node:crypto';
import {getTransactionDecoder} from '@solana/kit';
import {AppError} from './rpc.ts';
import {journalRead,journalWrite,journalValues} from './journal.ts';
import {transactionSync} from './storage.ts';
export interface ReviewedProgram {programId:string;sha256:string;genesisHash:string;}
export interface PreparedRecord {id:string;action:string;wallet:string;expiresAt:number;lastValidBlockHeight?:number;status?:string;error?:string;bond?:string;account?:string;params?:Record<string,unknown>;metadata?:Record<string,unknown>;signature?:string;chainStatus?:string;projectionStatus?:'pending'|'complete';programRelease?:ReviewedProgram;}
function identity(base64:string){try{const transaction=getTransactionDecoder().decode(Buffer.from(base64,'base64'));return createHash('sha256').update(Buffer.from(transaction.messageBytes)).digest('hex');}catch{throw new AppError('INVALID_TRANSACTION','The reviewed message cannot be decoded');}}
export function findPrepared(id:string){return /^[a-f0-9]{64}$/.test(id)?journalRead<PreparedRecord>('prepared',id):null;}
export function rememberPrepared(base64:string,details:Omit<PreparedRecord,'id'|'expiresAt'>){return transactionSync(()=>{const id=identity(base64);if(journalRead('operations',id))throw new AppError('RECOVERY_ID_CONFLICT','This message identifier belongs to an existing demo operation. Preserve its existing receipt and use its original recovery flow.',409);const existing=findPrepared(id);if(existing?.signature)return id;const values=journalValues<PreparedRecord>('prepared');const unresolved=values.filter(r=>r.signature&&r.chainStatus!=='error'&&(r.chainStatus!=='confirmed'||r.projectionStatus!=='complete'));if(unresolved.length>=100)throw new AppError('RECOVERY_CAPACITY','Resolve existing submitted operations before preparing another message',409);const unsigned=values.filter(r=>!r.signature&&r.expiresAt>Date.now()&&r.id!==id);if(unsigned.length>=128)throw new AppError('PREPARATION_CAPACITY','Wait for unsigned previews to expire or finish the existing operation',429);journalWrite('prepared',id,{...details,id,status:'prepared',expiresAt:Date.now()+120000});return id;});}
export function requirePrepared(base64:string){return transactionSync(()=>{const id=identity(base64),record=findPrepared(id);if(!record)throw new AppError('UNRECOGNIZED_TRANSACTION','Only the exact message prepared by BondTrace may be relayed',403);if(journalRead('operations',id))throw new AppError('RECOVERY_ID_CONFLICT','This legacy identifier belongs to two different operations. Preserve both records and recover any known transaction by its signature; do not sign either action again.',409);if(record.expiresAt<Date.now()&&!record.signature)throw new AppError('PREPARATION_EXPIRED','Prepare a fresh unsigned review; this message has not been relayed');return record;});}
export function completePrepared(id:string,signature:string){transactionSync(()=>{const record=findPrepared(id);if(!record)throw new AppError('UNRECOGNIZED_TRANSACTION','Prepared metadata disappeared before submission',409);if(record.signature&&record.signature!==signature)throw new AppError('OPERATION_CONFLICT','The reviewed message already has a different retained receipt',409);journalWrite('prepared',id,{...record,signature,status:'pending',chainStatus:'pending',projectionStatus:'pending'});});}
export function setPreparedStatus(id:string,status:string,error?:string){transactionSync(()=>{const record=findPrepared(id);if(record)journalWrite('prepared',id,{...record,status,chainStatus:status,...(error?{error}:{}),...(status==='error'?{projectionStatus:'complete'}:{})});});}
export function completePreparedProjection(id:string){transactionSync(()=>{const record=findPrepared(id);if(record)journalWrite('prepared',id,{...record,status:'confirmed',chainStatus:'confirmed',projectionStatus:'complete',error:undefined});});}
