import {TOKEN_PROGRAM_ADDRESS} from '@solana-program/token';
import {PROGRAM_ID,ata,decodeBond,decodeCoupon,decodeProposal,derive} from '../packages/client/src/program.ts';
import {entitlement,hasClaim} from '../packages/client/src/domain.ts';
import {account,AppError,chainClock} from './rpc.ts';
import {activities,fixture} from './store.ts';
import {demoEnabled,network,rpcUrl} from './config.ts';
export async function programAccount(key:string){const data=await account(key);if(!data.value)return null;if(data.value.owner!==PROGRAM_ID||data.value.executable)throw new AppError('INVALID_ACCOUNT_OWNER','Program state has an unexpected owner');return {bytes:Buffer.from(data.value.data[0],'base64'),slot:data.slot};}
export async function readBond(){const f=fixture();if(!f)return null;const raw=await programAccount(f.bond);if(!raw)return null;const bond=decodeBond(raw.bytes);if(bond.issuer!==f.roles.issuer||bond.seriesId.toString()!==f.seriesId||bond.settlementMint!==f.settlementMint)throw new AppError('FIXTURE_MISMATCH','Recorded instrument does not match on-chain identity');return {bond,address:f.bond,fixture:f};}
export async function tokenAmount(key:string,mint:string,allowClosedCanonical=false){const {value}=await account(key);if(!value)return 0n;const bytes=Buffer.from(value.data[0],'base64');if(allowClosedCanonical&&value.owner==='11111111111111111111111111111111'&&bytes.length===0)return 0n;if(value.owner!==TOKEN_PROGRAM_ADDRESS)throw new AppError('INVALID_TOKEN_OWNER','Token account has an unexpected program owner');if(bytes.length!==165)throw new AppError('INVALID_TOKEN_ACCOUNT','Expected classic SPL token account');const token=await import('@solana-program/token');const decoded=token.getTokenDecoder().decode(bytes);if(decoded.mint!==mint)throw new AppError('WRONG_TOKEN_MINT','Token mint mismatch');return decoded.amount;}
export async function getState(){
  const clock=await chainClock();const f=fixture();const result:any={network,rpcUrl,programId:PROGRAM_ID,connected:true,serverTime:new Date(Number(clock.timestamp)*1000).toISOString(),instrument:null,holders:[],coupons:[],redemption:null,proposals:[],activity:activities(),demo:{available:demoEnabled,ready:false,accelerated:true,roleWallets:f?.roles??{}}};
  const read=await readBond();if(!read)return result;const {bond,address:bondAddress}=read;
  const holderAtas=await Promise.all(bond.holderWallets.map(wallet=>ata(wallet,bond.bondMint)));
  const amounts=await Promise.all(holderAtas.map(key=>tokenAmount(key,bond.bondMint,true)));
  const label=(wallet:string)=>Object.entries(f!.roles).find(([,key])=>key===wallet)?.[0].replace('issuer','Test issuer').replace('investor','Test investor ')??'Registered holder';
  result.holders=bond.holderWallets.map((wallet,i)=>({wallet,label:label(wallet),units:amounts[i].toString()}));
  result.instrument={address:bondAddress,name:bond.name,symbol:'BOND·TEST',issuer:bond.issuer,bondMint:bond.bondMint,settlementMint:bond.settlementMint,faceValueMinor:bond.faceValue.toString(),rateBps:f!.rateBps,couponFrequency:f!.couponFrequency,status:['draft','active','redeeming','redeemed'][bond.state],issuedSupply:bond.totalIssued.toString(),redeemedSupply:bond.totalRedeemed.toString(),recordAt:new Date(Number(bond.couponTerms[0].recordTs)*1000).toISOString(),paymentAt:new Date(Number(bond.couponTerms[0].paymentTs)*1000).toISOString(),maturityAt:new Date(Number(bond.maturityTs)*1000).toISOString(),vaultBalanceMinor:(await tokenAmount(bond.vault,bond.settlementMint)).toString()};
  for(let index=0;index<bond.couponTerms.length;index++){
    const terms=bond.couponTerms[index], key=await derive('coupon',bondAddress,index), raw=await programAccount(key), snapshot=raw?decodeCoupon(raw.bytes):null;
    if(snapshot&&(snapshot.bond!==bondAddress||snapshot.index!==index||snapshot.unitAmount!==terms.unitAmount||snapshot.units.length!==bond.holderWallets.length))throw new AppError('INVALID_COUPON','Coupon account does not match instrument terms');
    const units=snapshot?.units??amounts;const rows=bond.holderWallets.map((wallet,i)=>({wallet,units:units[i].toString(),amountMinor:entitlement(terms.unitAmount,units[i]).toString(),claimed:snapshot?hasClaim(snapshot.claimedMask,i):false}));
    const total=rows.reduce((sum,row)=>sum+BigInt(row.amountMinor),0n), paid=snapshot?.paidTotal??0n;
    const creation=result.activity.find((item:any)=>item.account===key&&item.kind==='capture_coupon');
    result.coupons.push({id:String(index),snapshotAddress:snapshot?key:'',recordAt:new Date(Number(terms.recordTs)*1000).toISOString(),paymentAt:new Date(Number(terms.paymentTs)*1000).toISOString(),capturedAt:snapshot?new Date(Number(snapshot.capturedAt)*1000).toISOString():null,recordSlot:creation?.slot??'',totalMinor:total.toString(),paidMinor:paid.toString(),status:!snapshot?'scheduled':paid===total?'completed':clock.timestamp>=terms.paymentTs?'funded':'recorded',entitlements:rows});
  }
  if(bond.state>=2){const rows=bond.holderWallets.map((wallet,i)=>({wallet,units:bond.redemptionUnits[i].toString(),amountMinor:entitlement(bond.faceValue,bond.redemptionUnits[i]).toString(),claimed:hasClaim(bond.principalClaimedMask,i)}));result.redemption={snapshotAddress:bondAddress,totalMinor:rows.reduce((s,r)=>s+BigInt(r.amountMinor),0n).toString(),paidMinor:rows.filter(r=>r.claimed).reduce((s,r)=>s+BigInt(r.amountMinor),0n).toString(),entitlements:rows};}
  for(const id of f!.proposalIds){const key=await derive('proposal',bondAddress,BigInt(id)),raw=await programAccount(key);if(!raw)continue;const p=decodeProposal(raw.bytes);if(p.bond!==bondAddress||p.proposalId.toString()!==id||p.units.length!==bond.holderWallets.length)throw new AppError('INVALID_PROPOSAL','Proposal account does not match instrument');result.proposals.push({id,title:p.title,snapshotAddress:key,deadlineAt:new Date(Number(p.closesAt)*1000).toISOString(),yesWeight:p.yesUnits.toString(),noWeight:p.noUnits.toString(),eligibleWeights:bond.holderWallets.map((wallet,i)=>({wallet,units:p.units[i].toString()})),votedWallets:bond.holderWallets.filter((_wallet,i)=>hasClaim(p.ballotMask,i)),status:clock.timestamp>=p.closesAt?'closed':'open'});}
  result.demo.ready=f!.complete;return result;
}
