import {activityFile,fixtureFile,network,rpcUrl} from './config.ts';
import {readJson,writeJson,transactionSync} from './storage.ts';
import {receipt,saveReceipt,receipts} from './journal.ts';
export interface Fixture {seriesId:string;bond:string;name:string;settlementMint:string;createdAt:string;rateBps:number;couponFrequency:number;roles:Record<string,string>;proposalIds:string[];complete:boolean;accelerated:boolean;bootstrapSignature?:string;}
export interface Activity {signature:string;time:string;kind:string;status:string;slot?:number|null;explorerUrl:string;account?:string;bond?:string;verification?:string;}
export function jsonWrite(file:string,value:unknown){writeJson(file,value);}
export function fixture():Fixture|null{return readJson<Fixture|null>(fixtureFile,null);}
export function saveFixture(value:Fixture){writeJson(fixtureFile,value);}
export function recordProposal(bond:string,id:string){transactionSync(()=>{const value=fixture();if(value?.bond===bond&&!value.proposalIds.includes(id)){value.proposalIds.push(id);saveFixture(value);}});}
export function activities():Activity[]{return receipts().map(r=>({signature:r.signature,time:r.observedAt??r.submittedAt,kind:r.action,status:r.chainStatus,slot:r.slot??null,account:r.account,bond:r.bond,verification:r.verification,explorerUrl:r.network==='devnet'?'https://explorer.solana.com/tx/'+r.signature+'?cluster=devnet':'https://explorer.solana.com/tx/'+r.signature+'?cluster=custom&customUrl='+encodeURIComponent(rpcUrl)})).sort((a,b)=>Date.parse(b.time)-Date.parse(a.time));}
export function recordActivity(value:Activity){transactionSync(()=>{const prior=receipt(value.signature);saveReceipt({...prior,signature:value.signature,action:value.kind,network:prior?.network??network,genesisHash:prior?.genesisHash??null,projectionStatus:prior?.projectionStatus??'pending',submittedAt:prior?.submittedAt??value.time,chainStatus:value.status==='confirmed'?'confirmed':value.status==='error'?'error':value.status==='unknown'?'unknown':'pending',...(value.status==='confirmed'?{observedAt:value.time}:{}),slot:value.slot??prior?.slot??null,account:value.account??prior?.account,bond:value.bond??prior?.bond,verification:prior?.verification??'legacy-unbound'});});}
